create table User
(userId VARCHAR2(50) PRIMARY KEY,
userPwd VARCHAR2(50) NOT NULL,
userEmail VARCHAR2(50) NOT NULL UNIQUE,
userPhone VARCHAR2(50) NOT NULL,
userAddr VARCHAR2(100) NOT NULL,
REGDATE DATE);
